spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
  security:
    user:
      password: shah
springdoc:
  default-produces-media-type: application/json

server:
  servlet:
    context-path: /api/v1/
logging:
  level:
    org:
      springframework:
        security: DEBUG